"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import shutil
import os
from pathlib import Path

# find docker path
dockerPath = str(Path(shutil.which("docker")).parent)
currentPath = os.environ["PATH"]
newPath = currentPath + ":" + dockerPath


APP = ['gui.py']
DATA_FILES = ["data/cropped-FGHomeOffice-1.png"]
OPTIONS = {"iconfile": "data/icon.icns",
            "plist": {
                "CFBundleName": "FGO-Scheduler",
                "CFBundleDisplayName": "FGO-Scheduler",
                "LSEnvironment": {"PATH": newPath},
                "PyRuntimeLocations" : [
                "@executable_path/../Frameworks/libpython3.7.dylib",
                "/opt/anaconda3/envs/stream/lib/libpython3.7m.dylib",
                ]
            }}



setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
